[package]
name = "runner"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "runner"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

runner_integrity = { workspace = true } 
